language: go
sudo: false

matrix:
  include:
    - go: "1.10.x"
      script: go test -v ./...
    - go: "1.11.x"
      script: go test -v -mod=vendor ./...

go_import_path: github.com/dragouf/imageproxy

env:
  - GO111MODULE=on

install: true
